title: Tristan Uren # your name (or website title) here
logo: "/images/TempPortfolioLogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  A portfolio to showcase personal projects and those completed on Codecademy. 
  <br><br>
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
